### ISSUE TITLE
Over estimating size of targets

### ISSUE THREAD

**Issue by zachkendrick** [octoenigma/lidar_camera_calibration#10]
Have you found that the algorithm slightly over estimates the side lengths of the targets by about 1cm or so? It's causing the calibration to be off...

**Comment by ankitdhall** [comment]
Yes, while testing we also encountered a slight difference in the length of the sides (+-1cm if I remember correctly). It could cause a slight error but multiple iterations should be able to deal with that and mitigate its effect.
