### ISSUE TITLE
setup requirements

### ISSUE THREAD

**Issue by wzhouuu** [octoenigma/lidar_camera_calibration#11]
I just started looking for some good calibration toolboxes. I'm wondering if there's any requirement for ArUco marker? Where should I find the best choice of this marker? Also, is this toolbox working for both stereo and monocular cameras? Does it work for multiple cameras (say more than 2)? Thanks!

**Comment by ankitdhall** [comment]
You can read about the ArUco markers here: http://docs.opencv.org/3.1.0/d5/dae/tutorial_aruco_detection.html. This link can be used to generate the markers (http://terpconnect.umd.edu/~jwelsh12/enes100/markergen.html). Yes, `lidar_camera_calibration` should work with monocular, stereo and multiple cameras. You can find more information and illustrations about it in the README.md file.
