### ISSUE TITLE
cross_sensor_calibration/launch does not exist...

### ISSUE THREAD

**Issue by zachkendrick** [octoenigma/lidar_camera_calibration#2]
Hi,

Really cool ROS package! I like the approach using AR tags. I built the package but I am having issues running it. The directory cross_sensor_calibration/launch does not exist. I was wondering if you could add this or clarify where the new launch file is. Please note that I am fairly new to ROS so I am not an expert in launching ROS nodes.

Thanks!

**Comment by zachkendrick** [comment]
I think in the tutorial you meant to put `$ roslaunch lidar_camera_calibration find_transform.launch` as the command to run the ros node.

**Comment by ankitdhall** [comment]
thank you @zachkendrick
There were some typos in the README.md file, which have been edited.
Yes, the command to run the node is `roslaunch lidar_camera_calibration find_transform.launch`
