### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by zachkendrick** [octoenigma/lidar_camera_calibration#4]
I had the following issues when building your code and I thought it might be useful for you to know:

* **_Problem_**: fatal error: pcap.h: No such file or directory compilation terminated.    **_Solution_**: $ Sudo not-get instal libpcap0.8-dev

* **_Problem_**: In Corners.cpp could not find ros::package   **_Solution_**: Insert the following line #include<ros/package.h>

**Comment by ankitdhall** [comment]
@zachkendrick thanks
yeah you can install pcap with that command if you do not already have the library
